kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config-kvass
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: custom2
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ["alertmanager:9093"]
    rule_files:
    - /etc/prometheus/rules.yml
    remote_write:    # 写入到远程 VM 存储，url 是远程写入接口地址
    - url: http://vminsert:8480/insert/0/prometheus/
      # queue_config:    # 如果 Prometheus 抓取指标很大，可以加调整 queue，但是会提高内存占用
      #   max_samples_per_send: 10000  # 每次发送的最大样本数
      #   capacity: 20000
      #   max_shards: 30   # 最大分片数，即并发量。

    scrape_configs:
    - job_name: node-exporter
      scrape_interval: 3s
      honor_labels: true
      consul_sd_configs:
      - server: consul:8500
        services: [lima-rancher-desktop_node-exporter]
      relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,_app=([^,]+),.*
        replacement: ${1}
        target_label: _app
      - source_labels: [__meta_consul_tags]
        regex: .*,_service=([^,]+),.*
        replacement: ${1}
        target_label: _service
      - source_labels: [__meta_consul_tags]
        regex: .*,_hostname=([^,]+),.*
        replacement: ${1}
        target_label: _hostname
      - source_labels: [__meta_consul_tags]
        regex: .*,_environment=([^,]+),.*
        replacement: ${1}
        target_label: _environment

  rules.yml: |
    groups:
    - name: test-node-mem
      rules:
      - alert: NodeMemoryUsage
        expr: (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 > 20
        for: 2m
        labels:
          team: node
        annotations:
          summary: "{{$labels.instance}}: High Memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 20% (current value is: {{ $value }}"
