kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config-kvass
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: custom2
    scrape_configs:
    - job_name: "nodes"
      static_configs:
      - targets: ['192.168.205.2:9111']
      relabel_configs: # 通过 relabeling 从 __address__ 中提取 IP 信息，为了后面验证 VM 是否兼容 relabeling
      - source_labels: [__address__]
        regex: "(.*):(.*)"
        replacement: "${1}"
        target_label: 'ip'
        action: replace