apiVersion: v1
kind: Service
metadata:
  name: kvass-coordinator-incluster
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kvass-coordinator-incluster
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: kvass-coordinator-incluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kvass-coordinator-incluster
  name: kvass-coordinator-incluster
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kvass-coordinator-incluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kvass-coordinator-incluster
    spec:
      serviceAccountName: prometheus-incluster
      containers:
        - image: tkestack/kvass:v0.3.1
          name: kvass
          imagePullPolicy: Always
          args:
            - coordinator
            # - --shard.max-series=30000 # max series per shard
            - --shard.selector=app.kubernetes.io/name=prometheus-incluster # selector to get shard StatefulSets
            - --shard.namespace=$(NAMESPACE) # namespace to select shard StatefulSets
            - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
            - --shard.max-idle-time=0 # max time to wait before idle shard removed, 0 means shard never removed
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config
            - mountPath: /etc/prometheus/config_out
              name: config-out
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 20Mi

        - name: config-reload
          args:
            - --reload-url=http://localhost:9090/-/reload
            - --config-file=/etc/prometheus/config/prometheus.yml
            - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
          image: rancher/coreos-prometheus-config-reloader:v0.32.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
            requests:
              memory: 10Mi
          volumeMounts:
            - mountPath: /etc/prometheus/config_out
              name: config-out
            - mountPath: /etc/prometheus/config
              name: config
      volumes:
        - name: config
          configMap:
            name: prometheus-config-incluster
            defaultMode: 420
        - emptyDir: {}
          name: config-out
