apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: monitoring
  labels:
    app: consul
    component: server
spec:
  serviceName: consul
  replicas: 1
  selector:
    matchLabels:
      app: consul
      component: server
  template:
    metadata:
      labels:
        app: consul
        component: server
    spec:
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: consul-config
      containers:
      - name: consul
        image: consul:1.14.3
        imagePullPolicy: IfNotPresent
        args:
          - "agent"
          - "-server"                  # 以server加入集群
          - "-bootstrap-expect=1"      # 组成集群预期需要的数量
          - "-config-dir=/etc/consul/config"                     #配置文件目录，所有以.json结尾的文件都会被加载，可以是服务或consul自身的配置
          - "-advertise=$(PODIP)"      # 节点地址
          - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"   # 对已知地址情况下，启动时加入的另一位代理的地址
          # - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
          # - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
        volumeMounts:
          - name: consul
            mountPath: /consul/data
          - name: host-time
            mountPath: /etc/localtime
          - name: config
            mountPath: /etc/consul/config
        env:
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 8500     # HTTP API 及 Web UI
            name: http
          - containerPort: 8300     #  Server RPC，server 用于接受其他 agent 的请求
            name: server
          - containerPort: 8301     # Serf LAN，数据中心内 gossip 交换数据用
            name: serflan
          - containerPort: 8302     # Serf WAN，跨数据中心 gossip 交换数据用
            name: serfwan
          - containerPort: 8400     # CLI RPC，接受命令行的 RPC 调用
            name: cli-port
          - containerPort: 8600     # DNS 服务，可以把它配置到 53 端口来响应 dns 请求
            name: consuldns
  volumeClaimTemplates:
  - metadata:
      name: consul
      namespace: monitoring
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: longhorn

