language: node_js
node_js:
- '11'
addons:
  sonarcloud:
    organization: soprasteria
cache:
  directories:
  - "$HOME/.sonar/cache"
  - node_modules
install:
- npm install
script:
- npm test
- node index.js --help
deploy:
  provider: npm
  email: konstantin.sidorenko@orange.fr
  skip_cleanup: true
  api_key:
    secure: qCL/oKHRamDvMMw6dX8zKTZbJpScyRvouBqDNmlOqkaQs1KKCZVLkN/QoFmuzmK78KCj11gAvnz5035a6M4yL2rYTEkV6/WL56wil3FlDQQ5Yfbd4YEYD3g7eQ4ERqLRPSkfNDpvAAQ2FanRVHzpZn7RrUKmnWql2zs/clhWZjlyNShiNKEaeIrb2bzhabVP8pYINT5sRE5cbeODuImE6oTkbT02vorXU1R0E7RZpa3v49tCU+dsfyvOKZtHADCeqjmzlC1v7ncFL4bk4rpynvqvDAVtLRmYcK1CmpfP0Mr1q/RjFCrfAK628pNdEUiQnOTARTV1RtxiADWE03bGHZAgGW4bsuUUYjiApgDa/IiBQnF6Apg9G+0ZzIIFf/OFvXNb7blzybeRgrPobLP8Wtc8SXC1r3nsHLDQHsuqm4HHVjJbmeowYipPVePa3o4Kf6QOEnh6mlDpdhs4Z2yK1fXWZU8hTpzc9YBKN5ZMonu5C0v88vRqDYxU2neFszdnq1ceU7wrHEj3XtJ42yjWadmNDcgZAEc+m5H16Oq+EhbwWJ1ELFoNZpgXBSe8GB1TxRohfd1/6ghvuc0cl9B0uHpyh4GwbGZxDAT0GnuBW2qVQXUvWdcrVcn2vuBSH+M54BGwWxgjq8b9ti1mQADqybaKBJ6jY6U7Y+sqh/KFwX8=
  on:
    tag: true
    all_branches: true
